### ISSUE TITLE
Research Email Updates

### ISSUE THREAD

**Issue by bbmcmann** [hack4impact-calpoly/sloBotanicalGarden22#48]
The admins would like to receive an email whenever a volunteer reaches their milestone volunteer hours.
A node package is probably the easiest solution.

Please research:
- How easily can we control when emails are sent?
- How easy is it to change who receives the emails?
- Can admins interact via the email sent or do they have to login to acknowledge milestones? (this is less important but may be a plus)

Will meet with Ben and Ritvik quickly to discuss findings.

**Comment by ellabuysse** [comment]
Nodemailer
https://nodemailer.com/about/
https://www.npmjs.com/package/nodemailer
